// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu5XPJxr6LASzFIJD6Zvhn5QsdrbULLpg',
    appId: '1:1008304341302:web:b40df783e9aeaeb2e17397',
    messagingSenderId: '1008304341302',
    projectId: 'mynotes-flutter-roshan',
    authDomain: 'mynotes-flutter-roshan.firebaseapp.com',
    storageBucket: 'mynotes-flutter-roshan.appspot.com',
    measurementId: 'G-LJ7ZZV7VTN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqZw86nv0ZGrD6ebfJLNMPuH963HYjnwo',
    appId: '1:1008304341302:android:502fc41ab30ad328e17397',
    messagingSenderId: '1008304341302',
    projectId: 'mynotes-flutter-roshan',
    storageBucket: 'mynotes-flutter-roshan.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOVVfsVm2dHE36zEhs5cQR_-Tgk-_6T_w',
    appId: '1:1008304341302:ios:d30f89c2318cbefee17397',
    messagingSenderId: '1008304341302',
    projectId: 'mynotes-flutter-roshan',
    storageBucket: 'mynotes-flutter-roshan.appspot.com',
    iosClientId: '1008304341302-e57d8nh7otu6k1i7vggj8i0m10lo1cib.apps.googleusercontent.com',
    iosBundleId: 'com.roshan.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOVVfsVm2dHE36zEhs5cQR_-Tgk-_6T_w',
    appId: '1:1008304341302:ios:d30f89c2318cbefee17397',
    messagingSenderId: '1008304341302',
    projectId: 'mynotes-flutter-roshan',
    storageBucket: 'mynotes-flutter-roshan.appspot.com',
    iosClientId: '1008304341302-e57d8nh7otu6k1i7vggj8i0m10lo1cib.apps.googleusercontent.com',
    iosBundleId: 'com.roshan.mynotes',
  );
}
